# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-11 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=32, null=True, verbose_name='挂载路径')),
                ('size', models.CharField(blank=True, max_length=16, null=True, verbose_name='大小/G')),
                ('remarks', models.CharField(blank=True, max_length=2048, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '磁盘表',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, max_length=64, null=True, verbose_name='主机名')),
                ('ip', models.CharField(blank=True, max_length=32, null=True, verbose_name='IP地址')),
                ('cpu', models.CharField(blank=True, max_length=32, null=True, verbose_name='CPU')),
                ('mem', models.CharField(blank=True, max_length=16, null=True, verbose_name='内存')),
                ('is_vm', models.CharField(blank=True, max_length=8, null=True, verbose_name='是否虚拟机')),
                ('master_ip', models.CharField(blank=True, max_length=32, null=True, verbose_name='宿主机IP')),
                ('server_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='服务器型号')),
                ('os', models.CharField(blank=True, max_length=16, null=True, verbose_name='系统')),
                ('server_role', models.CharField(blank=True, max_length=32, null=True, verbose_name='服务器角色')),
                ('manage_ip', models.CharField(blank=True, max_length=32, null=True, verbose_name='管理IP')),
                ('sn', models.CharField(blank=True, max_length=16, null=True, verbose_name='序列号')),
                ('service_id', models.CharField(blank=True, max_length=16, null=True, verbose_name='快速服务代码')),
                ('disk', models.ManyToManyField(blank=True, null=True, to='cmdb.Disk', verbose_name='磁盘')),
            ],
            options={
                'verbose_name_plural': '主机表',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('passwd', models.CharField(max_length=32, verbose_name='密码')),
                ('prosition', models.CharField(blank=True, max_length=16, null=True, verbose_name='职位')),
            ],
            options={
                'verbose_name_plural': '用户表',
            },
        ),
    ]
