# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-12 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20190211_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=16, null=True, verbose_name='主机组名')),
            ],
            options={
                'verbose_name_plural': '主机组表',
            },
        ),
        migrations.AddField(
            model_name='host',
            name='program',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='运行程序'),
        ),
    ]
